'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("San_Antonio_NOM_Pass_Resort.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2480f9b3_f188_4592_9e81_955c757644e6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2480f9b3_f188_4592_9e81_955c757644e6", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _50cbbc13_2a26_48c6_b059_6dd94dd22c00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_50cbbc13_2a26_48c6_b059_6dd94dd22c00", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _50cbbc13_2a26_48c6_b059_6dd94dd22c001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_50cbbc13_2a26_48c6_b059_6dd94dd22c001", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _50cbbc13_2a26_48c6_b059_6dd94dd22c002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_50cbbc13_2a26_48c6_b059_6dd94dd22c002", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _50cbbc13_2a26_48c6_b059_6dd94dd22c003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_50cbbc13_2a26_48c6_b059_6dd94dd22c003", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _51325ba8_f3bc_42d3_9eec_504d45316d1f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_51325ba8_f3bc_42d3_9eec_504d45316d1f", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _51325ba8_f3bc_42d3_9eec_504d45316d1f1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_51325ba8_f3bc_42d3_9eec_504d45316d1f1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _531580981() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_531580981", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5315809811() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5315809811", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5315809812() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5315809812", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7f346973_16e1_460a_ab73_35f143d7bc8e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7f346973_16e1_460a_ab73_35f143d7bc8e", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _863ddd18_06e3_448e_8aa3_d6c3760816ca_removebg_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_863ddd18_06e3_448e_8aa3_d6c3760816ca_removebg_preview", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _863ddd18_06e3_448e_8aa3_d6c3760816ca_removebg_preview__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_863ddd18_06e3_448e_8aa3_d6c3760816ca_removebg_preview__1_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _863ddd18_06e3_448e_8aa3_d6c3760816ca_removebg_preview__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_863ddd18_06e3_448e_8aa3_d6c3760816ca_removebg_preview__1_1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c9afda80_bbd5_46d7_bc29_8d9fc3d79c77() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c9afda80_bbd5_46d7_bc29_8d9fc3d79c77", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dbeb3be8_2a3f_48b0_86fb_168010585fe7_Atlantis_Palm_underwatersuite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dbeb3be8_2a3f_48b0_86fb_168010585fe7_Atlantis_Palm_underwatersuite", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dd3078cb_1317_4455_8127_47ff5e890576() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dd3078cb_1317_4455_8127_47ff5e890576", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__1_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__2_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__3_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__4_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__5_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__6_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__7_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___1__8_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___1__8_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___2__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___2__1_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___2__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___2__2_", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desktop___2__2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop___2__2_1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edb90d34_f7b5_4f10_90ed_6174f5ecc61f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edb90d34_f7b5_4f10_90ed_6174f5ecc61f", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property formBookingBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formBookingBG", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property formBookingBG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formBookingBG1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property formBookingBG2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formBookingBG2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property formRoomsBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formRoomsBG", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property formRoomsBG2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formRoomsBG2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oyo_963_hotel_rumaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oyo_963_hotel_rumaya", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oyo_963_hotel_rumaya1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oyo_963_hotel_rumaya1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pixlr_image_generator_9cb97b40_308b_4ff0_a740_50c8997564db() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pixlr_image_generator_9cb97b40_308b_4ff0_a740_50c8997564db", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pixlr_image_generator_9cb97b40_308b_4ff0_a740_50c8997564db1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pixlr_image_generator_9cb97b40_308b_4ff0_a740_50c8997564db1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preview", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Queennn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queennn", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property single_room() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("single_room", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property singleee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("singleee", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property twin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twin", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
